from fastapi import status


class StatusCodes:
    CREATED = status.HTTP_201_CREATED
    OK = status.HTTP_200_OK
    BAD_REQUEST = status.HTTP_400_BAD_REQUEST
    NOT_FOUND = status.HTTP_404_NOT_FOUND


class ErrorCodes:
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_ACCOUNT_BLOCKED = "AUTH_ACCOUNT_BLOCKED"
    SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED"
    FEATURE_NOT_ALLOWED = "FEATURE_NOT_ALLOWED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"


STATUSES = StatusCodes()
error_codes = ErrorCodes()

__all__ = ["STATUSES", "error_codes"]
