class Tags:
    ORG_IDENTITY = "ACCOUNT-ACCES"
    ORG_CUSTOM = "ORG-CUSTOM"
    ORG_SUBSCRIPTION = "ORG-SUBSCRIPTION"

    ACCOUNT_ACCESS = "ACCOUNT-ACCES"
    ACCOUNT_CUSTOM = "ACCOUNT-CUSTOM"
    ACCOUNT_IDENTITY = "ACCOUNT-IDENTITY"

    INVENTORY = "INVENTORY"


TAGS = Tags()

__all__ = ["TAGS"]
